In [4]:
#creating the master dataset by combining 2025+(Jan2026,Feb,2026) prices of all the chemicals

In [5]:
import pandas as pd
import os

In [6]:
folder = "/Users/mangalyaphaye/Desktop/suvira_intelligence/data/processed"

files = [
"urea_monthly.csv",
"kcl_monthly.csv",
"sulphur_monthly.csv",
"sulphuric_acid_monthly.csv",
"acetic_acid_monthly.csv",
"pac_monthly.csv",
"formates_monthly.csv",
"wtc_monthly.csv"
]

dfs = []

for f in files:
    df = pd.read_csv(os.path.join(folder, f))
    dfs.append(df)

master_df = pd.concat(dfs, ignore_index=True)

In [7]:
master_df.shape

(96, 5)

In [8]:
master_df.head(20)

          date        netWgt      fobvalue  price_usd_per_ton chemical
0   2025-01-01  2.410698e+09  9.121906e+08         378.392783     Urea
1   2025-02-01  2.078211e+09  8.511858e+08         409.576215     Urea
2   2025-03-01  2.028980e+09  8.429866e+08         415.473015     Urea
3   2025-04-01  1.788448e+09  7.657576e+08         428.168873     Urea
4   2025-05-01  1.575915e+09  7.023316e+08         445.666004     Urea
5   2025-06-01  1.491557e+09  6.411226e+08         429.834522     Urea
6   2025-07-01  1.164113e+09  5.036376e+08         432.636352     Urea
7   2025-08-01  8.807778e+08  4.024460e+08         456.921122     Urea
8   2025-09-01  9.997098e+08  4.653524e+08         465.487518     Urea
9   2025-10-01  1.178613e+09  5.249220e+08         445.372827     Urea
10  2025-11-01  5.390459e+08  2.231218e+08         413.919777     Urea
11  2025-12-01  2.246168e+08  9.022838e+07         401.699173     Urea
12  2025-01-01  2.700396e+09  7.308552e+08         270.647387      KCL
13  2025-02-01  2.012568e+09  5.511922e+08         273.875007      KCL
14  2025-03-01  2.745972e+09  7.449051e+08         271.271892      KCL
15  2025-04-01  2.853118e+09  7.837140e+08         274.686905      KCL
16  2025-05-01  2.771009e+09  7.893451e+08         284.858394      KCL
17  2025-06-01  2.844069e+09  8.325128e+08         292.718926      KCL
18  2025-07-01  3.042544e+09  9.207338e+08         302.619691      KCL
19  2025-08-01  3.044241e+09  9.129746e+08         299.902262      KCL

In [9]:
master_df["chemical"].unique()

array(['Urea', 'KCL', 'Sulphur', 'Sulphuric Acid', 'Acetic Acid', 'PAC',
       'Formates', 'Water Treatment Chemicals'], dtype=object)

In [10]:
master_df.to_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/data/master_data_chemical_prices_2025.csv", index=False)

In [11]:
#Adding Jan-Feb data (2026)

In [27]:
master_df = pd.read_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/data/master_data_chemical_prices_2025.csv")
master_df.head()

         date        netWgt      fobvalue  price_usd_per_ton chemical
0  2025-01-01  2.410698e+09  9.121906e+08         378.392783     Urea
1  2025-02-01  2.078211e+09  8.511858e+08         409.576215     Urea
2  2025-03-01  2.028980e+09  8.429866e+08         415.473015     Urea
3  2025-04-01  1.788448e+09  7.657576e+08         428.168873     Urea
4  2025-05-01  1.575915e+09  7.023316e+08         445.666004     Urea

In [28]:
master_df.tail(10)

,date,netWgt,fobvalue,price_usd_per_ton,chemical
86,2025-03-01,6.413626e+08,2.361138e+09,3681.439944,Water Treatment Chemicals
87,2025-04-01,8.261912e+08,2.988128e+09,3616.751186,Water Treatment Chemicals
88,2025-05-01,8.344926e+08,2.820205e+09,3379.544661,Water Treatment Chemicals
89,2025-06-01,6.254936e+08,2.077436e+09,3321.275038,Water Treatment Chemicals
90,2025-07-01,6.867828e+08,2.315171e+09,3371.037794,Water Treatment Chemicals
91,2025-08-01,5.914354e+08,1.984388e+09,3355.207307,Water Treatment Chemicals
92,2025-09-01,7.749195e+08,2.699151e+09,3483.136952,Water Treatment Chemicals
93,2025-10-01,6.990152e+08,2.286073e+09,3270.419193,Water Treatment Chemicals
94,2025-11-01,3.055631e+08,1.242525e+09,4066.343839,Water Treatment Chemicals
95,2025-12-01,1.726437e+08,7.513792e+08,4352.195184,Water Treatment Chemicals

In [29]:
#January
jan_2026 = pd.DataFrame([
["2026-01-01", None, None, None, "Urea"],
["2026-01-01", None, None, None, "KCL"],
["2026-01-01", None, None, None, "Sulphur"],
["2026-01-01", None, None, None, "Sulphuric Acid"],
["2026-01-01", None, None, None, "Acetic Acid"],
["2026-01-01", None, None, None, "PAC"],
["2026-01-01", None, None, None, "Formates"],
["2026-01-01", None, None, None, "Water Treatment Chemicals"]
], columns=master_df.columns)

jan_2026

         date netWgt fobvalue price_usd_per_ton                   chemical
0  2026-01-01   None     None              None                       Urea
1  2026-01-01   None     None              None                        KCL
2  2026-01-01   None     None              None                    Sulphur
3  2026-01-01   None     None              None             Sulphuric Acid
4  2026-01-01   None     None              None                Acetic Acid
5  2026-01-01   None     None              None                        PAC
6  2026-01-01   None     None              None                   Formates
7  2026-01-01   None     None              None  Water Treatment Chemicals

In [30]:
master_df = pd.concat([master_df, jan_2026], ignore_index=True)

/var/folders/9s/w7j8ywnj0f7445fjtfdm26j00000gn/T/ipykernel_15504/3301796519.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_df = pd.concat([master_df, jan_2026], ignore_index=True)

In [31]:
master_df.tail(10)

,date,netWgt,fobvalue,price_usd_per_ton,chemical
94,2025-11-01,3.055631e+08,1.242525e+09,4066.343839,Water Treatment Chemicals
95,2025-12-01,1.726437e+08,7.513792e+08,4352.195184,Water Treatment Chemicals
96,2026-01-01,NaN,NaN,NaN,Urea
97,2026-01-01,NaN,NaN,NaN,KCL
98,2026-01-01,NaN,NaN,NaN,Sulphur
99,2026-01-01,NaN,NaN,NaN,Sulphuric Acid
100,2026-01-01,NaN,NaN,NaN,Acetic Acid
101,2026-01-01,NaN,NaN,NaN,PAC
102,2026-01-01,NaN,NaN,NaN,Formates
103,2026-01-01,NaN,NaN,NaN,Water Treatment Chemicals

In [32]:
#February
feb_2026 = pd.DataFrame([
["2026-02-01", None, None, None, "Urea"],
["2026-02-01", None, None, None, "KCL"],
["2026-02-01", None, None, None, "Sulphur"],
["2026-02-01", None, None, None, "Sulphuric Acid"],
["2026-02-01", None, None, None, "Acetic Acid"],
["2026-02-01", None, None, None, "PAC"],
["2026-02-01", None, None, None, "Formates"],
["2026-02-01", None, None, None, "Water Treatment Chemicals"]
], columns=master_df.columns)

feb_2026

         date netWgt fobvalue price_usd_per_ton                   chemical
0  2026-02-01   None     None              None                       Urea
1  2026-02-01   None     None              None                        KCL
2  2026-02-01   None     None              None                    Sulphur
3  2026-02-01   None     None              None             Sulphuric Acid
4  2026-02-01   None     None              None                Acetic Acid
5  2026-02-01   None     None              None                        PAC
6  2026-02-01   None     None              None                   Formates
7  2026-02-01   None     None              None  Water Treatment Chemicals

In [33]:
master_df = pd.concat([master_df, feb_2026], ignore_index=True)

/var/folders/9s/w7j8ywnj0f7445fjtfdm26j00000gn/T/ipykernel_15504/1611652303.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  master_df = pd.concat([master_df, feb_2026], ignore_index=True)

In [34]:
master_df.tail(16)

,date,netWgt,fobvalue,price_usd_per_ton,chemical
96,2026-01-01,NaN,NaN,NaN,Urea
97,2026-01-01,NaN,NaN,NaN,KCL
98,2026-01-01,NaN,NaN,NaN,Sulphur
99,2026-01-01,NaN,NaN,NaN,Sulphuric Acid
100,2026-01-01,NaN,NaN,NaN,Acetic Acid
101,2026-01-01,NaN,NaN,NaN,PAC
102,2026-01-01,NaN,NaN,NaN,Formates
103,2026-01-01,NaN,NaN,NaN,Water Treatment Chemicals
104,2026-02-01,NaN,NaN,NaN,Urea
105,2026-02-01,NaN,NaN,NaN,KCL
106,2026-02-01,NaN,NaN,NaN,Sulphur
107,2026-02-01,NaN,NaN,NaN,Sulphuric Acid
108,2026-02-01,NaN,NaN,NaN,Acetic Acid
109,2026-02-01,NaN,NaN,NaN,PAC
110,2026-02-01,NaN,NaN,NaN,Formates
111,2026-02-01,NaN,NaN,NaN,Water Treatment Chemicals

In [35]:
master_df.shape

(112, 5)

In [ ]:
#updating the spot values manually from spot values of the chemicals. (*Ask Tushar sir)

In [36]:
updates = [
("2026-01-01", "Urea", 520),
("2026-01-01", "Sulphur", 430),
("2026-01-01", "Acetic Acid", 660),

("2026-02-01", "Urea", 530),
("2026-02-01", "Sulphur", 450),
("2026-02-01", "Acetic Acid", 700)
]

for date, chem, price in updates:
    master_df.loc[
        (master_df["date"] == date) & (master_df["chemical"] == chem),
        "price_usd_per_ton"
    ] = price

In [37]:
master_df.tail(20)

,date,netWgt,fobvalue,price_usd_per_ton,chemical
92,2025-09-01,7.749195e+08,2.699151e+09,3483.136952,Water Treatment Chemicals
93,2025-10-01,6.990152e+08,2.286073e+09,3270.419193,Water Treatment Chemicals
94,2025-11-01,3.055631e+08,1.242525e+09,4066.343839,Water Treatment Chemicals
95,2025-12-01,1.726437e+08,7.513792e+08,4352.195184,Water Treatment Chemicals
96,2026-01-01,NaN,NaN,520.000000,Urea
97,2026-01-01,NaN,NaN,NaN,KCL
98,2026-01-01,NaN,NaN,430.000000,Sulphur
99,2026-01-01,NaN,NaN,NaN,Sulphuric Acid
100,2026-01-01,NaN,NaN,660.000000,Acetic Acid
101,2026-01-01,NaN,NaN,NaN,PAC
102,2026-01-01,NaN,NaN,NaN,Formates
103,2026-01-01,NaN,NaN,NaN,Water Treatment Chemicals
104,2026-02-01,NaN,NaN,530.000000,Urea
105,2026-02-01,NaN,NaN,NaN,KCL
106,2026-02-01,NaN,NaN,450.000000,Sulphur
107,2026-02-01,NaN,NaN,NaN,Sulphuric Acid
108,2026-02-01,NaN,NaN,700.000000,Acetic Acid
109,2026-02-01,NaN,NaN,NaN,PAC
110,2026-02-01,NaN,NaN,NaN,Formates
111,2026-02-01,NaN,NaN,NaN,Water Treatment Chemicals

In [ ]:
#will soon update the prices of remianing chemicals according to the data recieved (*Ask tushar sir)

In [38]:
# Add Sulphuric Acid prices
updates_sa = [
("2026-01-01", "Sulphuric Acid", 240),
("2026-02-01", "Sulphuric Acid", 240)
]

for date, chem, price in updates_sa:
    master_df.loc[
        (master_df["date"] == date) & (master_df["chemical"] == chem),
        "price_usd_per_ton"
    ] = price

In [39]:
master_df.tail(20)

,date,netWgt,fobvalue,price_usd_per_ton,chemical
92,2025-09-01,7.749195e+08,2.699151e+09,3483.136952,Water Treatment Chemicals
93,2025-10-01,6.990152e+08,2.286073e+09,3270.419193,Water Treatment Chemicals
94,2025-11-01,3.055631e+08,1.242525e+09,4066.343839,Water Treatment Chemicals
95,2025-12-01,1.726437e+08,7.513792e+08,4352.195184,Water Treatment Chemicals
96,2026-01-01,NaN,NaN,520.000000,Urea
97,2026-01-01,NaN,NaN,NaN,KCL
98,2026-01-01,NaN,NaN,430.000000,Sulphur
99,2026-01-01,NaN,NaN,240.000000,Sulphuric Acid
100,2026-01-01,NaN,NaN,660.000000,Acetic Acid
101,2026-01-01,NaN,NaN,NaN,PAC
102,2026-01-01,NaN,NaN,NaN,Formates
103,2026-01-01,NaN,NaN,NaN,Water Treatment Chemicals
104,2026-02-01,NaN,NaN,530.000000,Urea
105,2026-02-01,NaN,NaN,NaN,KCL
106,2026-02-01,NaN,NaN,450.000000,Sulphur
107,2026-02-01,NaN,NaN,240.000000,Sulphuric Acid
108,2026-02-01,NaN,NaN,700.000000,Acetic Acid
109,2026-02-01,NaN,NaN,NaN,PAC
110,2026-02-01,NaN,NaN,NaN,Formates
111,2026-02-01,NaN,NaN,NaN,Water Treatment Chemicals

In [40]:
master_df.to_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/data/master_dataset_2026.csv", index=False)

In [ ]:
#Next steps: ARIMA framework: 03_arima_model.ipynb