In [1]:
import pandas as pd
df_pred = pd.read_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/outputs/sarimax_predictions_v2.csv")
df_pred

                    Chemical  Predicted Price (USD/ton)
0                       Urea                     520.98
1                        KCL                     464.13
2                    Sulphur                     512.97
3             Sulphuric Acid                     342.61
4                Acetic Acid                     700.33
5                        PAC                     442.35
6                   Formates                    1315.13
7  Water Treatment Chemicals                    4353.75

In [2]:
df_pred["Manual Price (USD/ton)"] = None

In [3]:
df_pred["Final Price (USD/ton)"] = df_pred["Manual Price (USD/ton)"].fillna(df_pred["Predicted Price (USD/ton)"])

/var/folders/9s/w7j8ywnj0f7445fjtfdm26j00000gn/T/ipykernel_29082/2847966016.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_pred["Final Price (USD/ton)"] = df_pred["Manual Price (USD/ton)"].fillna(df_pred["Predicted Price (USD/ton)"])

In [5]:
df_pred.to_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/outputs/final_prices_v3.csv", index=False)

In [6]:
df_pred.isna().sum()

Chemical                     0
Predicted Price (USD/ton)    0
Manual Price (USD/ton)       8
Final Price (USD/ton)        0
dtype: int64

In [7]:
df_pred[["Chemical", "Predicted Price (USD/ton)", "Final Price (USD/ton)"]]

                    Chemical  Predicted Price (USD/ton)  Final Price (USD/ton)
0                       Urea                     520.98                 520.98
1                        KCL                     464.13                 464.13
2                    Sulphur                     512.97                 512.97
3             Sulphuric Acid                     342.61                 342.61
4                Acetic Acid                     700.33                 700.33
5                        PAC                     442.35                 442.35
6                   Formates                    1315.13                1315.13
7  Water Treatment Chemicals                    4353.75                4353.75

In [ ]:
# This system is designed to predict chemical prices using a multi-stage approach:

# 1. Baseline Model (ARIMA):
#    Captures historical price trends.

# 2. Enhanced Model (SARIMAX):
#    Incorporates macroeconomic factors such as oil prices,
#    natural gas prices, and geopolitical events to improve prediction realism.

# 3. Manual Adjustment Layer:
#    Allows integration of real-time vendor inputs to override or refine model predictions,
#    making the system adaptable to dynamic market conditions.

# This layered approach ensures both data-driven insights and practical usability in real-world scenarios.

# Limitation:
# Model predictions depend on historical data patterns and proxy macro inputs.
# Real-time vendor data integration will further improve accuracy.