In [7]:
#merging both models arima and sarimax for comparisons
#model evaluations: arima gave accurate values of MAPE for 6/8 chemicals but sarimax gave better results as in prediction values<10% or error for 6/8 chemicals.
import pandas as pd
import numpy as np

In [8]:
arima_df = pd.read_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/outputs/final_arima_results.csv")
sarimax_df = pd.read_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/outputs/final_sarimax_results.csv")

arima_df.head(), sarimax_df.head()

(                    Chemical         MAE        RMSE       MAPE
 0                   Formates   92.282348  104.987712   6.684949
 1                        KCL   32.993765   48.866261   8.367556
 2                       Urea   50.125642   53.727800  12.145446
 3  Water Treatment Chemicals  579.710296  657.050199  14.108433
 4                Acetic Acid   68.843753   72.044456  17.338582,
       Chemical        MAE       RMSE       MAPE
 0     Formates  65.689203  74.274241   4.905884
 1  Acetic Acid  32.393039  35.415042   7.504050
 2          KCL  38.821862  54.634944  10.253816
 3      Sulphur  32.398335  34.359768  10.756044
 4         Urea  47.775119  57.438735  11.535947)

In [9]:
arima_df = arima_df.rename(columns={
    "MAE": "ARIMA_mae",
    "RMSE": "ARIMA_rmse",
    "MAPE": "ARIMA_mape"
})

sarimax_df = sarimax_df.rename(columns={
    "MAE": "SARIMAX_mae",
    "RMSE": "SARIMAX_rmse",
    "MAPE": "SARIMAX_mape"
})

arima_df.head(), sarimax_df.head()

(                    Chemical   ARIMA_mae  ARIMA_rmse  ARIMA_mape
 0                   Formates   92.282348  104.987712    6.684949
 1                        KCL   32.993765   48.866261    8.367556
 2                       Urea   50.125642   53.727800   12.145446
 3  Water Treatment Chemicals  579.710296  657.050199   14.108433
 4                Acetic Acid   68.843753   72.044456   17.338582,
       Chemical  SARIMAX_mae  SARIMAX_rmse  SARIMAX_mape
 0     Formates    65.689203     74.274241      4.905884
 1  Acetic Acid    32.393039     35.415042      7.504050
 2          KCL    38.821862     54.634944     10.253816
 3      Sulphur    32.398335     34.359768     10.756044
 4         Urea    47.775119     57.438735     11.535947)

In [10]:
comparison_df = pd.merge(arima_df, sarimax_df, on="Chemical")
comparison_df

,Chemical,ARIMA_mae,ARIMA_rmse,ARIMA_mape,SARIMAX_mae,SARIMAX_rmse,SARIMAX_mape
0,Formates,92.282348,104.987712,6.684949,65.689203,74.274241,4.905884
1,KCL,32.993765,48.866261,8.367556,38.821862,54.634944,10.253816
2,Urea,50.125642,53.727800,12.145446,47.775119,57.438735,11.535947
3,Water Treatment Chemicals,579.710296,657.050199,14.108433,497.276519,644.946678,12.042053
4,Acetic Acid,68.843753,72.044456,17.338582,32.393039,35.415042,7.504050
5,Sulphur,57.395320,57.819612,18.633826,32.398335,34.359768,10.756044
6,Sulphuric Acid,30.818416,40.759106,20.174304,28.321711,38.945545,19.381190
7,PAC,87.374456,112.615329,27.051244,68.255311,93.380230,20.320888

In [11]:
comparison_df["Best Model"] = np.where(comparison_df["SARIMAX_mape"] < comparison_df["ARIMA_mape"],"SARIMAX","ARIMA")
comparison_df

,Chemical,ARIMA_mae,ARIMA_rmse,ARIMA_mape,SARIMAX_mae,SARIMAX_rmse,SARIMAX_mape,Best Model
0,Formates,92.282348,104.987712,6.684949,65.689203,74.274241,4.905884,SARIMAX
1,KCL,32.993765,48.866261,8.367556,38.821862,54.634944,10.253816,ARIMA
2,Urea,50.125642,53.727800,12.145446,47.775119,57.438735,11.535947,SARIMAX
3,Water Treatment Chemicals,579.710296,657.050199,14.108433,497.276519,644.946678,12.042053,SARIMAX
4,Acetic Acid,68.843753,72.044456,17.338582,32.393039,35.415042,7.504050,SARIMAX
5,Sulphur,57.395320,57.819612,18.633826,32.398335,34.359768,10.756044,SARIMAX
6,Sulphuric Acid,30.818416,40.759106,20.174304,28.321711,38.945545,19.381190,SARIMAX
7,PAC,87.374456,112.615329,27.051244,68.255311,93.380230,20.320888,SARIMAX

In [13]:
#creating a unified pipeline to automate choosing which prediction model is better for which chemical according to it's pattern
comparison_df.to_csv("/Users/mangalyaphaye/Desktop/suvira_intelligence/outputs/model_comparison.csv", index=False)